/**
 * The schemas in this directory are designed to be simpler versions (hence why some are commented out)
 * Of the AI SDK ModelMessage (https://ai-sdk.dev/docs/reference/ai-sdk-core/model-message) Types,
 * and to be compatible with the streamText and generateText functions.
 *
 * Use these inferred types to format messages going TO models.
 */

import type {
  AssistantModelMessage as SdkAssistantModelMessage,
  ModelMessage as SdkModelMessage,
  SystemModelMessage as SdkSystemModelMessage,
  ToolModelMessage as SdkToolModelMessage,
  UserModelMessage as SdkUserModelMessage,
} from "ai";
import { z } from "zod";

// --- Base Content Schemas ---

/**
 * A schema for data content that can be represented in multiple ways.
 * Used for images and files.
 */
const strandweaveDataContentSchema = z.union([
  z.string().describe("Base64-encoded string"),
  z.instanceof(Uint8Array),
  z.instanceof(ArrayBuffer),
  z.instanceof(Buffer), // For Node.js environments
]);

/**
 * JSON value schema compatible with the AI SDK JSONValue type.
 * Allows null, primitive types, arrays and objects with string keys.
 */
type JsonValue = null | string | number | boolean | { [k: string]: JsonValue } | JsonValue[];
const jsonValueSchema: z.ZodType<JsonValue> = z.lazy(() =>
  z.union([
    z.null(),
    z.string(),
    z.number(),
    z.boolean(),
    z.array(jsonValueSchema),
    z.record(jsonValueSchema),
  ]),
);

/**
 * Tool result "content" value parts (used when output.type === 'content').
 * Aligns with LanguageModelV2ToolResultOutput content parts.
 */
const strandweaveToolResultContentValueSchema = z.array(
  z.discriminatedUnion("type", [
    z.object({ type: z.literal("text"), text: z.string() }).strict(),
    z.object({ type: z.literal("media"), data: z.string(), mediaType: z.string() }).strict(),
  ]),
);

/**
 * Output schema for tool results, aligned with LanguageModelV2ToolResultOutput.
 */
const strandweaveToolResultOutputSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("text"), value: z.string() }).strict(),
  z.object({ type: z.literal("json"), value: jsonValueSchema }).strict(),
  z.object({ type: z.literal("error-text"), value: z.string() }).strict(),
  z.object({ type: z.literal("error-json"), value: jsonValueSchema }).strict(),
  z.object({ type: z.literal("content"), value: strandweaveToolResultContentValueSchema }).strict(),
]);

// --- ModelMessage Part Schemas ---

/**
 * Represents a text part of a message.
 */
export const strandweaveTextPartSchema = z
  .object({
    type: z.literal("text"),
    text: z.string(),
  })
  .strict();

/**
 * Represents an image part in a user message.
 */
export const strandweaveImagePartSchema = z
  .object({
    type: z.literal("image"),
    image: z.union([strandweaveDataContentSchema, z.instanceof(URL)]),
    mediaType: z.string().optional(),
  })
  .strict();

/**
 * Represents a file part in a user or assistant message.
 */
export const strandweaveFilePartSchema = z
  .object({
    type: z.literal("file"),
    data: z.union([strandweaveDataContentSchema, z.instanceof(URL)]),
    mediaType: z.string(),
    filename: z.string().optional(),
  })
  .strict();

/**
 * Represents a tool call generated by the model.
 */
export const strandweaveToolCallPartSchema = z
  .object({
    type: z.literal("tool-call"),
    toolCallId: z.string(),
    toolName: z.string(),
    input: z.record(jsonValueSchema).describe("Arguments for the tool call"),
  })
  .strict();

/**
 * Represents the multi-part content of a tool result.
 */
const strandweaveToolResultContentSchema = strandweaveToolResultContentValueSchema;

/**
 * Represents the result of a tool's execution.
 */
export const strandweaveToolResultPartSchema = z
  .object({
    type: z.literal("tool-result"),
    toolCallId: z.string(),
    toolName: z.string(),
    output: strandweaveToolResultOutputSchema,
    experimental_content: strandweaveToolResultContentSchema.optional(),
    isError: z.boolean().optional(),
  })
  .strict();

// --- Full Message Schemas ---

/**
 * A system message for setting the model's behavior.
 */
export const strandweaveSystemModelMessageSchema = z
  .object({
    role: z.literal("system"),
    content: z.string(),
  })
  .strict();

/**
 * A user message, representing input from the end-user.
 */
export const strandweaveUserModelMessageSchema = z
  .object({
    role: z.literal("user"),
    content: z.union([
      z.string(),
      z.array(
        z.union([strandweaveTextPartSchema, strandweaveImagePartSchema, strandweaveFilePartSchema]),
      ),
    ]),
  })
  .strict();

/**
 * An assistant message, representing the response from the model.
 */
export const strandweaveAssistantModelMessageSchema = z
  .object({
    role: z.literal("assistant"),
    content: z.union([
      z.string(),
      z.array(z.union([strandweaveTextPartSchema, strandweaveToolCallPartSchema])),
    ]),
  })
  .strict();

/**
 * A tool message, providing the results of tool calls back to the model.
 */
export const strandweaveToolModelMessageSchema = z
  .object({
    role: z.literal("tool"),
    content: z.array(strandweaveToolResultPartSchema),
  })
  .strict();

// --- The All-Encompassing ModelMessage Schema ---

/**
 * The primary `StrandweaveModelMessage` schema.
 * It's a discriminated union of all possible message types, which is the most
 * efficient and type-safe way to validate objects with a shared `role` key.
 */
export const strandweaveModelMessageSchema = z.discriminatedUnion("role", [
  strandweaveSystemModelMessageSchema,
  strandweaveUserModelMessageSchema,
  strandweaveAssistantModelMessageSchema,
  strandweaveToolModelMessageSchema,
]);

// --- EXPORTED TYPES ---

export type StrandweaveModelMessage = z.infer<typeof strandweaveModelMessageSchema>;
export type StrandweaveSystemModelMessage = z.infer<typeof strandweaveSystemModelMessageSchema>;
export type StrandweaveUserModelMessage = z.infer<typeof strandweaveUserModelMessageSchema>;
export type StrandweaveAssistantModelMessage = z.infer<
  typeof strandweaveAssistantModelMessageSchema
>;
export type StrandweaveToolModelMessage = z.infer<typeof strandweaveToolModelMessageSchema>;

// --- BUILD-TIME TYPE VALIDATION ---
// This section ensures that our Zod schemas remain compatible with the official
// types from the `ai` SDK. It checks that our defined types are valid "subsets"
// of the SDK's types. If the `ai` package is updated with breaking changes,
// running `bun tc` will cause a compile-time error
// in this file, alerting us to update our schemas.

/**
 * A helper function for static type assertions.
 * It checks if StrandweaveType can be assigned to SdkType (i.e., is a valid subset).
 * This function has no runtime effect; its purpose is purely for static analysis.
 */
const assertStrandweaveIsSubsetOfSdk = <SdkType, _StrandweaveType extends SdkType>() => {};

// Check 1: Validate our main discriminated union against the SDK's.
assertStrandweaveIsSubsetOfSdk<SdkModelMessage, StrandweaveModelMessage>();

// Check 2: Validate each specific message type for more granular error reporting.
assertStrandweaveIsSubsetOfSdk<SdkSystemModelMessage, StrandweaveSystemModelMessage>();
assertStrandweaveIsSubsetOfSdk<SdkUserModelMessage, StrandweaveUserModelMessage>();
assertStrandweaveIsSubsetOfSdk<SdkAssistantModelMessage, StrandweaveAssistantModelMessage>();
assertStrandweaveIsSubsetOfSdk<SdkToolModelMessage, StrandweaveToolModelMessage>();
