import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Inlined templates for init command
 * These are bundled into the distribution to avoid path resolution issues
 */
const templates: Record<string, string> = {
  "strand.json": `{
  "meta": {
    "name": "My Workflow",
    "version": "1.0.0",
    "description": "Generated by strandweave init"
  },
  "recommendations": {
    "model": "haiku"
  },
  "strand": [
    {
      "id": "analyze-haiku",
      "name": "Analyze Project (Haiku)",
      "model": "haiku",
      "continuationMode": "fresh",
      "promptFile": "./prompts/analyze-haiku.md",
      "trackedFiles": ["analysis-haiku.md"],
      "outputFiles": [
        {
          "copy": ["analysis-haiku.md"]
        }
      ]
    },
    {
      "id": "analyze-gemini",
      "name": "Analyze Project (Gemini)",
      "model": "gemini-2.5-flash",
      "continuationMode": "fresh",
      "promptFile": "./prompts/analyze-gemini.md",
      "trackedFiles": ["analysis-gemini.md"],
      "outputFiles": [
        {
          "copy": ["analysis-gemini.md"]
        }
      ]
    }
  ]
}`,

  "prompts/analyze-haiku.md": `# Project Analysis (Haiku)

Please analyze the files in the \`data\` directory located in the current working directory (do not go to other directories) and create a comprehensive analysis report.

Your analysis should include:

1. Very brief overview of the files in that directory

Please create your analysis in a file called \`analysis-haiku.md\` in the execution directory.`,

  "prompts/analyze-gemini.md": `# Project Analysis (Gemini)

Please analyze the files in the \`data\` directory located in the current working directory (do not go to other directories) and create a comprehensive analysis report.

Your analysis should include:

1. Very brief overview of the files in that directory

Please create your analysis in a file called \`analysis-gemini.md\` in the execution directory.`,

  "README.md": `# Strand

This strand was initialized with \`strandweave init\`.

- \`strand.json\` - Main workflow configuration
- \`prompts/analyze.md\` - Prompt template for analysis
- \`.gitignore\` - Ignore patterns for version control

## Customization

Edit \`strand.json\` to customize your workflow:
- Add more codons to the \`strand\` array
- Change the \`model\` (sonnet or opus)
- Add \`rigSetup\` to prepare your environment
- Configure \`trackedFiles\` to monitor specific files
- Use \`recommendations\` to suggest runtime settings`,

  "data/sample1.txt": `# Project Overview

This is a sample project for demonstrating the strandweave workflow system.

## Key Features
- Multi-step AI workflows
- Flexible codon configuration
- File tracking and persistence

## Getting Started
1. Review the strand.json configuration
2. Customize prompts in the prompts/ directory
3. Run your workflow with strandweave`,

  "data/sample2.txt": `# Technical Specifications

## Architecture
- Node.js runtime
- TypeScript for type safety
- Event-driven processing model

## Dependencies
- bun for fast execution
- Anthropic Claude API for AI capabilities

## Configuration
The system uses JSON-based configuration files to define workflows and execution parameters.`,

  "data/notes.txt": `# Development Notes

## TODO
- Add more example workflows
- Improve error handling
- Add unit tests for core functionality

## Ideas
- Support for parallel codon execution
- Integration with other AI providers
- Web-based workflow designer

## Known Issues
- None at this time`,
};

/**
 * Initialize a new strand with basic template files
 */
export async function initProject(targetDir: string): Promise<void> {
  // Ensure target directory exists
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  // Check if directory is empty or only has .git
  const existingFiles = fs.readdirSync(targetDir);

  if (existingFiles.length > 0) {
    throw new Error(
      `Directory ${targetDir} is not empty. Please run init in an empty directory or specify a new directory.`,
    );
  }

  // Create prompts directory
  const promptsDir = path.join(targetDir, "prompts");
  fs.mkdirSync(promptsDir, { recursive: true });

  // Create data directory
  const dataDir = path.join(targetDir, "data");
  fs.mkdirSync(dataDir, { recursive: true });

  // Write template files from inlined content
  for (const [targetPath, content] of Object.entries(templates)) {
    const fullPath = path.join(targetDir, targetPath);
    const dir = path.dirname(fullPath);

    // Ensure parent directory exists
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(fullPath, content, "utf-8");
  }

  console.log(`\n✅ Initialized strand in ${targetDir}\n`);
  console.log("Created files:");
  console.log("  - strand.json");
  console.log("  - prompts/analyze-haiku.md");
  console.log("  - prompts/analyze-gemini.md");
  console.log("  - data/sample1.txt");
  console.log("  - data/sample2.txt");
  console.log("  - data/notes.txt");
  console.log("  - README.md");
}
